/**
 * ================================================================================================
 * TOOLTIPS CONFIG - Конфигурация всплывающих подсказок
 * ================================================================================================
 * Skill: app/skills/ux-principles
 */

(function() {
    'use strict';

    let currentLanguage = 'ru';

    const TOOLTIPS_RU = {
        'button.save.icon': 'Иконка: Сохранить',
        'button.save.text': 'Основной текст: Сохранить изменения',
        'button.delete.icon': 'Иконка: Удалить',
        'button.delete.text': 'Основной текст: Delete элемент',
        'button.load.icon': 'Иконка: Загрузить',
        'button.load.text': 'Основной текст: Загрузить файл',
        'button.settings.icon': 'Иконка: Настройки',
        'button.settings.text': 'Основной текст: Открыть настройки',
        'button.save-all.text': 'Основной текст: Сохранить все изменения',
        'button.settings-app.text': 'Основной текст: Открыть настройки приложения',
        'button.notifications.icon': 'Иконка: Уведомления',
        'button.notifications.text': 'Основной текст: Просмотр уведомлений',
        'button.notifications.suffix.badge': 'Суффикс: 5 новых уведомлений',
        'button.notifications.suffix.badge1': 'Суффикс 1: 5 новых уведомлений',
        'button.notifications.suffix.badge2': 'Суффикс 2: Новая функция',
        'button.export.icon': 'Иконка: Экспорт',
        'button.export.text': 'Основной текст: Экспорт данных',
        'button.export.suffix.icon': 'Суффикс: Открыть в новой вкладке',
        'button.connection.icon': 'Иконка: Соединение',
        'button.connection.text': 'Основной текст: Статус подключения',
        'button.connection.suffix.indicator': 'Суффикс: Статус: Активен',
        'button.menu.text': 'Основной текст: Раскрыть меню',
        'button.menu.suffix.chevron': 'Суффикс: Раскрыть/свернуть меню',
        'button.help.icon': 'Иконка: Справка',
        'button.help.text': 'Основной текст: Открыть справку',
        'button.help.suffix.info': 'Суффикс: Открыть справку',
        'dropdown.market-analytics.icon': 'Иконка: Аналитика рынков',
        'dropdown.market-analytics.text': 'Основной текст: Просмотр статистики',
        'dropdown.notifications.suffix.badge': 'Количество уведомлений',
        'dropdown.notifications.icon': 'Иконка: Уведомления',
        'dropdown.notifications.text': 'Основной текст: Просмотр уведомлений',
        'dropdown.system-settings.icon': 'Иконка: Настройки системы',
        'dropdown.system-settings.text': 'Основной текст: Конфигурация системы',
        'dropdown.export.suffix.icon': 'Открыть в новой вкладке',
        'dropdown.export.icon': 'Иконка: Экспорт',
        'dropdown.export.text': 'Основной текст: Экспорт данных',
        'dropdown.connection.suffix.indicator': 'Статус: Активен',
        'dropdown.connection.icon': 'Иконка: Соединение',
        'dropdown.connection.text': 'Основной текст: Статус подключения',
        'dropdown.settings.suffix.chevron.expand': 'Раскрыть подменю',
        'dropdown.settings.icon': 'Иконка: Настройки',
        'dropdown.settings.text': 'Основной текст: Настройки',
        'dropdown.settings.suffix.chevron.collapse': 'Свернуть подменю',
        'dropdown.analytics.suffix.info': 'Открыть справку',
        'dropdown.analytics.icon': 'Иконка: Аналитика',
        'dropdown.analytics.text': 'Основной текст: Расширенная аналитика',
        'dropdown.blocked.icon': 'Иконка: Заблокировано',
        'dropdown.blocked.text': 'Основной текст: Функция недоступна',
        'dropdown.document.suffix.badge': 'Новая функция',
        'dropdown.document.icon': 'Иконка: Документ',
        'dropdown.document.text': 'Основной текст: Длинный текст',
        'ui.coinSort.alphabet': 'по алфавиту (A→Z)',
        'ui.coinSort.marketCap': 'по капитализации',
        'ui.coinSort.volume': 'по объему торгов',
        'ui.coinSort.favorite': 'избранные',
        'ui.coinSort.selected': 'выбранные',
        'ui.coinSet.load': 'Загрузить набор монет',
        'ui.coinSet.save': 'Сохранить набор монет',
        'ui.refresh.soft': 'Update интерфейс (кэш актуален)',
        'ui.refresh.full': 'Update данные монет и метрик рынка',
        'ui.coinTable.showPrice': 'Показать Price',
        'ui.coinTable.hidePrice': 'Скрыть Price',
        'ui.vix.sourcePrefix': 'VIX источник:',
        'ui.vix.default': 'VIX Volatility Index',
        'ui.search.alreadyInTable': 'Уже в таблице',
        'ui.modal.missingCoins.title': 'Не найдены монеты',
        'ui.modal.portfolioForm.title': 'Формирование портфеля',
        'ui.modal.portfolioView.title': 'Просмотр портфеля',
        'ui.combobox.clear': 'Очистить',
        'ui.coinBlock.favorite.remove': 'Убрать',
        'ui.coinBlock.favorite.add': 'Добавить',
        'ui.coinBlock.open': 'Открыть',
        'ui.coinBlock.delete': 'Удалить',
        'ui.coinSet.draft.save': 'Сохранить черновик',
        'metric.horizonDays.description': 'ГП (Горизонт прогноза)\nВременной горизонт for расчета всех метрик.\nОпределяет, на какой период строится\nпрогноз изменения цены актива.',
        'metric.mdnHours.description': 'MDN Hours (Часы)\nГоризонт расчета индикатора\nрыночного направления (MDN).\nКраткосрочный сигнал "здесь и сейчас".',
        'metric.agrMethod.description': 'AGR Method (Метод)\nМетод расчета устойчивости тренда for AGR:\nDCS (направление), TSI (сила), MP (моментум).',
        'metric.columnVisibility.description': 'Видимость колонок\nУправление отображением групп колонок\nв таблице: основные показатели,\nволатильность, устойчивость и т.д.',
        'metric.columnVisibility.result.description': 'AGR: Adaptive Growth Rate\nMAX: Maximum Potential Value\nmin: Minimum Potential Value\nDCS: Direction Change Stability\nTSI: Trend Strength Indicator\nMPS: Momentum Preservation Stability\nCPT: Composite Performance\nDIN: Dynamic Impact',
        'metric.columnVisibility.percent.description': '% (Процентные изменения)\nПоказывает процентные изменения цены\nза различные периоды: 1h, 24h, 7d, 14d, 30d, 200d.\nПомогает оценить краткосрочную\nи долгосрочную динамику актива.',
        'metric.columnVisibility.complexDeltas.description': 'Компл. дельты (CD)\nНакопленные взвешенные изменения цены\nпо неделям (CD1w–CD6w) и на горизонте\nпрогноза (CDH). Показывают интегральную\nдинамику актива с учетом временных весов.',
        'metric.columnVisibility.gradients.description': 'Градиенты (CGR)\nВзвешенные градиенты изменения цены\nмежду временными узлами (CGR2–CGR6)\nи их сумма (CGR Σ). Показывают скорость\nи направление движения цены.',
        'metric.portfolioAccess.description': 'Мои портфели\nБыстрый доступ к созданным портфелям,\nпросмотр их текущей доходности\nи создание новых sets монет.',
        'metric.portfolioAccess.lsHeader': 'Счетчик L/S:',
        'metric.portfolioAccess.lsLong': 'Long (AGR ≥ 0)',
        'metric.portfolioAccess.lsShort': 'Short (AGR < 0)',
        'metric.mdn.description': 'MDN (Market Direction Now)\nИнтегральный индикатор текущего\nнаправления рынка. Учитывает медианы\nмоментума, тренда, ускорения\nи рыночные индикаторы.',
        'metric.medianCdh.description': 'Медиана CDH\nМедианное значение накопленной дельты\n(CDH) всех монет. Показывает средний\nпотенциал изменения цены на горизонте прогноза.\nПоложительное значение — бычий сигнал,\nотрицательное — медвежий.',
        'metric.medianCgr.description': 'Медиана CGR\nМедианное значение градиента изменения\nцены (CGR) всех монет. Показывает среднюю\nскорость движения рынка.\nПоложительное значение — ускорение роста,\nотрицательное — ускорение падения.',
        'metric.medianAgr.description': 'Медиана AGR\nМедианное значение адаптивной доходности\n(AGR) всех монет. Показывает средний потенциал\nгодовой доходности с учетом устойчивости тренда.\nПоложительное значение — бычий сигнал,\nотрицательное — медвежий.',
        'metric.longShort.description': 'Long/Short\nСоотношение количества монет\nс бычьими и медвежьими сигналами.\nПоказывает ширину рынка — насколько широко\nраспределены бычьи и медвежьи настроения\nсреди активов.',
        'metric.bullishPercent.description': 'Bullish Percent\nПроцент монет с положительной динамикой.\nПоказывает ширину бычьего рынка.\nВысокое значение (>50%) — широкий бычий рынок,\nнизкое (<50%) — узкий бычий рынок или медвежий.',
        'metric.cdhRatio.description': 'CDH P/N Ratio\nСоотношение положительных и отрицательных\nзначений CDH. Показывает баланс между бычьими\nи медвежьими сигналами по накопленной дельте.\n>1 — бычий баланс, <1 — медвежий.',
        'metric.cgrRatio.description': 'CGR P/N Ratio\nСоотношение положительных и отрицательных\nзначений CGR. Показывает баланс между\nускорением роста и падения.\n>1 — преобладает рост, <1 — преобладает падение.',
        'metric.agrRatio.description': 'AGR P/N Ratio\nСоотношение положительных и отрицательных\nзначений AGR. Показывает баланс между бычьими\nи медвежьими сигналами по адаптивной доходности.\n>1 — бычий баланс, <1 — медвежий.',
        'metric.dcs.description': 'DCS (Direction Change Stability)\nМетод расчета устойчивости тренда AGR\nна основе анализа изменения направления цены.\nПодходит for волатильных рынков.',
        'metric.tsi.description': 'TSI (Trend Strength Indicator)\nМетод расчета устойчивости тренда AGR\nна основе силы тренда. Подходит for\nстабильных трендовых движений.',
        'metric.mp.description': 'MPS (Momentum Preservation Stability)\nМетод расчета устойчивости тренда AGR\nна основе сохранения импульса.\nПодходит for импульсных рынков.',
        'metric.cdh.description': 'CDH (Complex Delta Horizon)\nНакопленная дельта цены на горизонте прогноза.\nПоказывает интегральное изменение цены\nс учетом всех временных периодов.',
        'metric.cgr.description': 'CGR (Complex Gradient Rate)\nКомплексный градиент изменения цены.\nПоказывает скорость и направление\nдвижения цены по всем узлам.',
        'metric.cgrDeg.description': 'CGR Degree (Степень градиента)\nСтепень изменения комплексного градиента.\nПоказывает интенсивность ускорения\nили замедления движения цены.',
        'metric.maxPV.description': 'Max PV (Maximum Potential Value)\nМаксимальное потенциальное изменение цены.\nПоказывает исторический максимум роста актива.',
        'metric.minPV.description': 'Min PV (Minimum Potential Value)\nМинимальное потенциальное изменение цены.\nПоказывает исторический максимум падения актива.',
        'metric.agr.description': 'AGR (Adaptive Growth Rate)\nГодовая доходность с учетом корреляции\nтрендов, роста, импульса и устойчивости.\nОсновной сигнал for выбора направления торговли.',
        'metric.din.description': 'DIN (Dynamic Impact)\nВзвешенное изменение цены с учетом\nрыночного фактора (FGI, BTC Dom, OI, FR, LSR)\nи импульса (CPT).',
        'metric.cpt.description': 'CPT (Composite Performance)\nКомпозитный импульс: взвешенное среднее\nизменений цены по всем временным узлам\nс учетом горизонта прогноза.',
        'metric.fgi.description': 'Fear & Greed Index (FGI)\nИндикатор страха и жадности на рынке\nкриптовалют. Помогает определить\nперекупленность или перепроданность рынка.\n\n© Alternative.me',
        'metric.btcDom.description': 'BTC Dominance\nДоля капитализации Bitcoin в общем рынке.\nПоказывает концентрацию капитала в BTC\nи степень риск-офф настроений.',
        'metric.oi.description': 'Open Interest (OI)\nОбщий объем открытых позиций на рынке деривативов.\nРост OI усиливает тренд,\nпадение OI сигнализирует о снижении интереса.',
        'metric.fr.description': 'Funding Rate (FR)\nСтавка финансирования бессрочных фьючерсов.\nПоложительная — доминируют Long,\nотрицательная — доминируют Short.',
        'metric.lsr.description': 'Long/Short Ratio (LSR)\nСоотношение Long и Short позиций.\n>1 — преобладают Long,\n<1 — преобладают Short.',
        'metric.vix.description': 'VIX (Volatility Index)\nИндекс волатильности фондового рынка США.\nРост VIX обычно означает рост страха\nи снижение аппетита к риску.'
    };

    const TOOLTIPS_EN = {
        'button.save.icon': 'Icon: Save',
        'button.save.text': 'Main Text: Save changes',
        'button.delete.icon': 'Icon: Delete',
        'button.delete.text': 'Main Text: Delete item',
        'button.load.icon': 'Icon: Load',
        'button.load.text': 'Main Text: Load file',
        'button.settings.icon': 'Icon: Settings',
        'button.settings.text': 'Main Text: Open settings',
        'button.save-all.text': 'Main Text: Save all changes',
        'button.settings-app.text': 'Main Text: Open app settings',
        'button.notifications.icon': 'Icon: Notifications',
        'button.notifications.text': 'Main Text: View notifications',
        'button.notifications.suffix.badge': 'Suffix: 5 new notifications',
        'button.notifications.suffix.badge1': 'Suffix 1: 5 new notifications',
        'button.notifications.suffix.badge2': 'Suffix 2: New feature',
        'button.export.icon': 'Icon: Export',
        'button.export.text': 'Main Text: Export data',
        'button.export.suffix.icon': 'Suffix: Open in new tab',
        'button.connection.icon': 'Icon: Connection',
        'button.connection.text': 'Main Text: Connection status',
        'button.connection.suffix.indicator': 'Suffix: Status: Active',
        'button.menu.text': 'Main Text: Expand menu',
        'button.menu.suffix.chevron': 'Suffix: Expand/collapse menu',
        'button.help.icon': 'Icon: Help',
        'button.help.text': 'Main Text: Open help',
        'button.help.suffix.info': 'Suffix: Open help',
        'dropdown.market-analytics.icon': 'Icon: Market Analytics',
        'dropdown.market-analytics.text': 'Main Text: View statistics',
        'dropdown.notifications.suffix.badge': 'Notification count',
        'dropdown.notifications.icon': 'Icon: Notifications',
        'dropdown.notifications.text': 'Main Text: View notifications',
        'dropdown.system-settings.icon': 'Icon: System Settings',
        'dropdown.system-settings.text': 'Main Text: System configuration',
        'dropdown.export.suffix.icon': 'Open in new tab',
        'dropdown.export.icon': 'Icon: Export',
        'dropdown.export.text': 'Main Text: Export data',
        'dropdown.connection.suffix.indicator': 'Status: Active',
        'dropdown.connection.icon': 'Icon: Connection',
        'dropdown.connection.text': 'Main Text: Connection status',
        'dropdown.settings.suffix.chevron.expand': 'Expand submenu',
        'dropdown.settings.icon': 'Icon: Settings',
        'dropdown.settings.text': 'Main Text: Settings',
        'dropdown.settings.suffix.chevron.collapse': 'Collapse submenu',
        'dropdown.analytics.suffix.info': 'Open help',
        'dropdown.analytics.icon': 'Icon: Analytics',
        'dropdown.analytics.text': 'Main Text: Advanced analytics',
        'dropdown.blocked.icon': 'Icon: Blocked',
        'dropdown.blocked.text': 'Main Text: Feature unavailable',
        'dropdown.document.suffix.badge': 'New feature',
        'dropdown.document.icon': 'Icon: Document',
        'dropdown.document.text': 'Main Text: Long text',
        'ui.coinSort.alphabet': 'alphabet (A→Z)',
        'ui.coinSort.marketCap': 'market cap',
        'ui.coinSort.volume': 'trading volume',
        'ui.coinSort.favorite': 'favorites',
        'ui.coinSort.selected': 'selected',
        'ui.coinSet.load': 'Load coin set',
        'ui.coinSet.save': 'Save coin set',
        'ui.refresh.soft': 'Refresh UI (cache is fresh)',
        'ui.refresh.full': 'Refresh coin data and market metrics',
        'ui.coinTable.showPrice': 'Show Price',
        'ui.coinTable.hidePrice': 'Hide Price',
        'ui.vix.sourcePrefix': 'VIX source:',
        'ui.vix.default': 'VIX Volatility Index',
        'ui.search.alreadyInTable': 'Already in table',
        'ui.modal.missingCoins.title': 'Coins not found',
        'ui.modal.portfolioForm.title': 'Portfolio formation',
        'ui.modal.portfolioView.title': 'Portfolio view',
        'ui.combobox.clear': 'Clear',
        'ui.coinBlock.favorite.remove': 'Remove',
        'ui.coinBlock.favorite.add': 'Add',
        'ui.coinBlock.open': 'Open',
        'ui.coinBlock.delete': 'Delete',
        'ui.coinSet.draft.save': 'Save draft',
        'metric.horizonDays.description': 'Horizon Days\nTime horizon for calculating all metrics.\nDetermines the period for asset price change forecast.',
        'metric.mdnHours.description': 'MDN Hours\nHorizon for calculating Market Direction Now (MDN) indicator.\nShort-term "here and now" signal.',
        'metric.agrMethod.description': 'AGR Method\nTrend stability calculation method for AGR:\nDCS (direction), TSI (strength), MP (momentum).',
        'metric.columnVisibility.description': 'Column Visibility\nControl the display of column groups in the table:\nmain metrics, volatility, stability, etc.',
        'metric.columnVisibility.result.description': 'AGR: Adaptive Growth Rate\nMAX: Maximum Potential Value\nmin: Minimum Potential Value\nDCS: Direction Change Stability\nTSI: Trend Strength Indicator\nMPS: Momentum Preservation Stability\nCPT: Composite Performance\nDIN: Dynamic Impact',
        'metric.columnVisibility.percent.description': '% (Price changes)\nShows price changes over various periods:\n1h, 24h, 7d, 14d, 30d, 200d.\nHelps evaluate short-term and long-term asset dynamics.',
        'metric.columnVisibility.complexDeltas.description': 'Complex Deltas (CD)\nAccumulated weighted price changes by weeks (CD1w–CD6w)\nand on the forecast horizon (CDH).\nShows integral asset dynamics with time weights.',
        'metric.columnVisibility.gradients.description': 'Gradients (CGR)\nWeighted price change gradients between time nodes (CGR2–CGR6)\nand their sum (CGR Σ). Shows the speed and direction of price movement.',
        'metric.portfolioAccess.description': 'My Portfolios\nQuick access to created portfolios,\nview their current yield and create new coin sets.',
        'metric.portfolioAccess.lsHeader': 'L/S Counter:',
        'metric.portfolioAccess.lsLong': 'Long (AGR ≥ 0)',
        'metric.portfolioAccess.lsShort': 'Short (AGR < 0)',
        'metric.mdn.description': 'MDN (Market Direction Now)\nIntegral indicator of the current market direction.\nTakes into account medians of momentum, trend,\nacceleration and market indicators.',
        'metric.medianCdh.description': 'Median CDH\nMedian value of accumulated delta (CDH) for all coins.\nShows the average price change potential on the forecast horizon.\nPositive value is a bullish signal, negative is bearish.',
        'metric.medianCgr.description': 'Median CGR\nMedian value of price change gradient (CGR) for all coins.\nShows the average speed of market movement.\nPositive value is acceleration of growth, negative is acceleration of fall.',
        'metric.medianAgr.description': 'Median AGR\nMedian value of adaptive yield (AGR) for all coins.\nShows the average annual yield potential considering trend stability.\nPositive value is a bullish signal, negative is bearish.',
        'metric.longShort.description': 'Long/Short\nRatio of coins with bullish and bearish signals.\nShows market breadth — how widely bullish and\nbearish sentiments are distributed among assets.',
        'metric.bullishPercent.description': 'Bullish Percent\nPercentage of coins with positive dynamics.\nShows bullish market breadth.\nHigh value (>50%) — broad bullish market,\nlow value (<50%) — narrow bullish market or bearish.',
        'metric.cdhRatio.description': 'CDH P/N Ratio\nRatio of positive to negative CDH values.\nShows the balance between bullish and bearish\nsignals by accumulated delta. >1 is bullish balance, <1 is bearish.',
        'metric.cgrRatio.description': 'CGR P/N Ratio\nRatio of positive to negative CGR values.\nShows the balance between acceleration of growth and fall.\n>1 growth prevails, <1 fall prevails.',
        'metric.agrRatio.description': 'AGR P/N Ratio\nRatio of positive to negative AGR values.\nShows the balance between bullish and bearish\nsignals by adaptive yield. >1 is bullish balance, <1 is bearish.',
        'metric.dcs.description': 'DCS (Direction Change Stability)\nAGR trend stability calculation method based on\nprice direction change analysis.\nSuitable for volatile markets.',
        'metric.tsi.description': 'TSI (Trend Strength Indicator)\nAGR trend stability calculation method based on\ntrend strength. Suitable for stable trend movements.',
        'metric.mp.description': 'MPS (Momentum Preservation Stability)\nAGR trend stability calculation method based on\nmomentum preservation. Suitable for momentum markets.',
        'metric.cdh.description': 'CDH (Complex Delta Horizon)\nAccumulated price delta on the forecast horizon.\nShows integral price change considering all time periods.',
        'metric.cgr.description': 'CGR (Complex Gradient Rate)\nComplex price change gradient.\nShows the speed and direction of price movement across all nodes.',
        'metric.cgrDeg.description': 'CGR Degree (Gradient Degree)\nDegree of complex gradient change.\nShows the intensity of price movement acceleration or deceleration.',
        'metric.maxPV.description': 'Max PV (Maximum Potential Value)\nMaximum potential price change.\nShows the historical maximum asset growth.',
        'metric.minPV.description': 'Min PV (Minimum Potential Value)\nMinimum potential price change.\nShows the historical maximum asset decline.',
        'metric.agr.description': 'AGR (Adaptive Growth Rate)\nAnnual yield considering trend correlation, growth,\nmomentum and stability. Main signal for choosing trade direction.',
        'metric.din.description': 'DIN (Dynamic Impact)\nWeighted price change considering market factors\n(FGI, BTC Dom, OI, FR, LSR) and momentum (CPT).',
        'metric.cpt.description': 'CPT (Composite Performance)\nComposite momentum: weighted average of price changes\nacross all time nodes considering the forecast horizon.',
        'metric.fgi.description': 'Fear & Greed Index (FGI)\nIndicator of market sentiment. Helps identify\nmarket overbought or oversold conditions.\n\n© Alternative.me',
        'metric.btcDom.description': 'BTC Dominance\nBitcoin market cap share in the total market.\nShows capital concentration in BTC\nand overall risk-off sentiment.',
        'metric.oi.description': 'Open Interest (OI)\nTotal open derivatives positions.\nRising OI strengthens trends,\nfalling OI signals waning interest.',
        'metric.fr.description': 'Funding Rate (FR)\nPerpetual futures funding rate.\nPositive — Longs dominate,\nnegative — Shorts dominate.',
        'metric.lsr.description': 'Long/Short Ratio (LSR)\nRatio of Long to Short positions.\n>1 — Longs dominate,\n<1 — Shorts dominate.',
        'metric.vix.description': 'VIX (Volatility Index)\nUS equity market volatility index.\nRising VIX usually signals fear\nand lower risk appetite.'
    };

    const TOOLTIPS_DE = {
        'button.save.icon': 'Symbol: Speichern',
        'button.save.text': 'Haupttext: Änderungen speichern',
        'button.delete.icon': 'Symbol: Löschen',
        'button.delete.text': 'Haupttext: Element löschen',
        'button.load.icon': 'Symbol: Laden',
        'button.load.text': 'Haupttext: Datei laden',
        'button.settings.icon': 'Symbol: Einstellungen',
        'button.settings.text': 'Haupttext: Einstellungen öffnen',
        'button.save-all.text': 'Haupttext: Alle Änderungen speichern',
        'button.settings-app.text': 'Haupttext: App-Einstellungen öffnen',
        'button.notifications.icon': 'Symbol: Benachrichtigungen',
        'button.notifications.text': 'Haupttext: Benachrichtigungen anzeigen',
        'button.notifications.suffix.badge': 'Suffix: 5 neue Benachrichtigungen',
        'button.notifications.suffix.badge1': 'Suffix 1: 5 neue Benachrichtigungen',
        'button.notifications.suffix.badge2': 'Suffix 2: Neue Funktion',
        'button.export.icon': 'Symbol: Export',
        'button.export.text': 'Haupttext: Daten exportieren',
        'button.export.suffix.icon': 'Suffix: In neuem Tab öffnen',
        'button.connection.icon': 'Symbol: Verbindung',
        'button.connection.text': 'Haupttext: Verbindungsstatus',
        'button.connection.suffix.indicator': 'Suffix: Status: Aktiv',
        'button.menu.text': 'Haupttext: Menü ausklappen',
        'button.menu.suffix.chevron': 'Suffix: Menü ein-/ausklappen',
        'button.help.icon': 'Symbol: Hilfe',
        'button.help.text': 'Haupttext: Hilfe öffnen',
        'button.help.suffix.info': 'Suffix: Hilfe öffnen',
        'dropdown.market-analytics.icon': 'Symbol: Marktanalyse',
        'dropdown.market-analytics.text': 'Haupttext: Statistiken anzeigen',
        'dropdown.notifications.suffix.badge': 'Anzahl Benachrichtigungen',
        'dropdown.notifications.icon': 'Symbol: Benachrichtigungen',
        'dropdown.notifications.text': 'Haupttext: Benachrichtigungen anzeigen',
        'dropdown.system-settings.icon': 'Symbol: Systemeinstellungen',
        'dropdown.system-settings.text': 'Haupttext: Systemkonfiguration',
        'dropdown.export.suffix.icon': 'In neuem Tab öffnen',
        'dropdown.export.icon': 'Symbol: Export',
        'dropdown.export.text': 'Haupttext: Daten exportieren',
        'dropdown.connection.suffix.indicator': 'Status: Aktiv',
        'dropdown.connection.icon': 'Symbol: Verbindung',
        'dropdown.connection.text': 'Haupttext: Verbindungsstatus',
        'dropdown.settings.suffix.chevron.expand': 'Untermenü öffnen',
        'dropdown.settings.icon': 'Symbol: Einstellungen',
        'dropdown.settings.text': 'Haupttext: Einstellungen',
        'dropdown.settings.suffix.chevron.collapse': 'Untermenü schließen',
        'dropdown.analytics.suffix.info': 'Hilfe öffnen',
        'dropdown.analytics.icon': 'Symbol: Analyse',
        'dropdown.analytics.text': 'Haupttext: Erweiterte Analyse',
        'dropdown.blocked.icon': 'Symbol: Gesperrt',
        'dropdown.blocked.text': 'Haupttext: Funktion nicht verfügbar',
        'dropdown.document.suffix.badge': 'Neue Funktion',
        'dropdown.document.icon': 'Symbol: Dokument',
        'dropdown.document.text': 'Haupttext: Langer Text',
        'ui.coinSort.alphabet': 'alphabetisch (A→Z)',
        'ui.coinSort.marketCap': 'Marktkapitalisierung',
        'ui.coinSort.volume': 'Handelsvolumen',
        'ui.coinSort.favorite': 'Favoriten',
        'ui.coinSort.selected': 'Ausgewählt',
        'ui.coinSet.load': 'Coin-Set laden',
        'ui.coinSet.save': 'Coin-Set speichern',
        'ui.refresh.soft': 'UI aktualisieren (Cache aktuell)',
        'ui.refresh.full': 'Coin-Daten und Marktmetriken aktualisieren',
        'ui.coinTable.showPrice': 'Preis anzeigen',
        'ui.coinTable.hidePrice': 'Preis ausblenden',
        'ui.vix.sourcePrefix': 'VIX-Quelle:',
        'ui.vix.default': 'VIX Volatilitätsindex',
        'ui.search.alreadyInTable': 'Bereits in Tabelle',
        'ui.modal.missingCoins.title': 'Coins nicht gefunden',
        'ui.modal.portfolioForm.title': 'Portfolio-Erstellung',
        'ui.modal.portfolioView.title': 'Portfolio-Ansicht',
        'ui.combobox.clear': 'Leeren',
        'ui.coinBlock.favorite.remove': 'Entfernen',
        'ui.coinBlock.favorite.add': 'Hinzufügen',
        'ui.coinBlock.open': 'Öffnen',
        'ui.coinBlock.delete': 'Löschen',
        'ui.coinSet.draft.save': 'Entwurf speichern',
        'metric.horizonDays.description': 'Horizont Tage\nZeithorizont für die Berechnung aller Metriken.\nBestimmt den Zeitraum der Preisprognose\nfür das Asset.',
        'metric.mdnHours.description': 'MDN Hours\nHorizont für die Berechnung des Market Direction Now (MDN).\nKurzfristiges „hier und jetzt“-Signal.',
        'metric.agrMethod.description': 'AGR Method\nMethode zur Berechnung der Trendstabilität für AGR:\nDCS (Richtung), TSI (Stärke), MP (Momentum).',
        'metric.columnVisibility.description': 'Spaltensichtbarkeit\nSteuert die Anzeige von Spaltengruppen\nin der Tabelle: Hauptmetriken,\nVolatilität, Stabilität usw.',
        'metric.columnVisibility.percent.description': '% (Preisänderungen)\nZeigt Preisänderungen über verschiedene Zeiträume:\n1h, 24h, 7d, 14d, 30d, 200d.\nHilft, kurz- und langfristige Dynamik\nzu bewerten.',
        'metric.columnVisibility.complexDeltas.description': 'Komplexe Deltas (CD)\nAkkumulierte gewichtete Preisänderungen\nnach Wochen (CD1w–CD6w) und auf dem\nPrognosehorizont (CDH). Zeigen die integrale\nDynamik des Assets mit Zeitgewichten.',
        'metric.columnVisibility.result.description': 'AGR: Adaptive Growth Rate\nMAX: Maximum Potential Value\nmin: Minimum Potential Value\nDCS: Direction Change Stability\nTSI: Trend Strength Indicator\nMPS: Momentum Preservation Stability\nCPT: Composite Performance\nDIN: Dynamic Impact',
        'metric.portfolioAccess.description': 'Meine Portfolios\nSchneller Zugriff auf erstellte Portfolios,\nAnzeige ihrer aktuellen Rendite\nund Erstellung neuer Coin-Sets.',
        'metric.portfolioAccess.lsHeader': 'L/S-Zähler:',
        'metric.portfolioAccess.lsLong': 'Long (AGR ≥ 0)',
        'metric.portfolioAccess.lsShort': 'Short (AGR < 0)',
        'metric.mdn.description': 'MDN (Market Direction Now)\nIntegraler Indikator der aktuellen Marktrichtung.\nBerücksichtigt Mediane von Momentum, Trend,\nBeschleunigung und Marktindikatoren.',
        'metric.medianCdh.description': 'Median CDH\nMedianwert der akkumulierten Delta (CDH)\naller Coins. Zeigt das durchschnittliche\nPreisänderungspotenzial auf dem Prognosehorizont.\nPositiv = bullisches Signal,\nnegativ = bärisch.',
        'metric.medianCgr.description': 'Median CGR\nMedianwert des Preisänderungsgradienten (CGR)\naller Coins. Zeigt die durchschnittliche\nGeschwindigkeit der Marktbewegung.\nPositiv = Beschleunigung des Wachstums,\nnegativ = Beschleunigung des Rückgangs.',
        'metric.medianAgr.description': 'Median AGR\nMedianwert der adaptiven Rendite (AGR)\naller Coins. Zeigt das durchschnittliche\nJahresrenditepotenzial unter Berücksichtigung\nder Trendstabilität. Positiv = bullisch,\nnegativ = bärisch.',
        'metric.longShort.description': 'Long/Short\nVerhältnis der Coins mit bullischen und\nbärischen Signalen. Zeigt die Marktbreite –\nwie breit bullische und bärische Stimmung\nunter den Assets verteilt sind.',
        'metric.bullishPercent.description': 'Bullish Percent\nProzentualer Anteil der Coins mit positiver\nDynamik. Zeigt die Breite des Bullenmarkts.\nHoher Wert (>50%) = breiter Bullenmarkt,\nniedriger (<50%) = enger Bullen- oder Bärenmarkt.',
        'metric.cdhRatio.description': 'CDH P/N Ratio\nVerhältnis positiver zu negativer CDH-Werte.\nZeigt das Gleichgewicht zwischen bullischen\nund bärischen Signalen. >1 bullisch, <1 bärisch.',
        'metric.cgrRatio.description': 'CGR P/N Ratio\nVerhältnis positiver zu negativer CGR-Werte.\nZeigt das Gleichgewicht zwischen Beschleunigung\nvon Wachstum und Rückgang. >1 Wachstum dominiert,\n<1 Rückgang dominiert.',
        'metric.agrRatio.description': 'AGR P/N Ratio\nVerhältnis positiver zu negativer AGR-Werte.\nZeigt das Gleichgewicht zwischen bullischen\nund bärischen Signalen der adaptiven Rendite.\n>1 bullisch, <1 bärisch.',
        'metric.dcs.description': 'DCS (Direction Change Stability)\nMethode zur Berechnung der AGR-Trendstabilität\nbasierend auf der Analyse von Richtungswechseln.\nGeeignet für volatile Märkte.',
        'metric.tsi.description': 'TSI (Trend Strength Indicator)\nMethode zur Berechnung der AGR-Trendstabilität\nbasierend auf Trendstärke. Geeignet für\nstabile Trendbewegungen.',
        'metric.mp.description': 'MPS (Momentum Preservation Stability)\nMethode zur Berechnung der AGR-Trendstabilität\nbasierend auf Momentum-Erhalt. Geeignet für\nMomentum-Märkte.',
        'metric.cdh.description': 'CDH (Complex Delta Horizon)\nAkkumulierte Preisdifferenz auf dem Prognosehorizont.\nZeigt die integrale Preisänderung unter\nBerücksichtigung aller Zeiträume.',
        'metric.cgr.description': 'CGR (Complex Gradient Rate)\nKomplexer Preisänderungsgradient.\nZeigt die Geschwindigkeit und Richtung\nder Preisbewegung über alle Knoten.',
        'metric.cgrDeg.description': 'CGR Degree (Gradientenstufe)\nStufe der Änderung des komplexen Gradienten.\nZeigt die Intensität der Beschleunigung\noder Verlangsamung der Preisbewegung.',
        'metric.maxPV.description': 'Max PV (Maximum Potential Value)\nMaximales potenzielles Preisänderungsausmaß.\nZeigt das historische maximale Wachstum des Assets.',
        'metric.minPV.description': 'Min PV (Minimum Potential Value)\nMinimales potenzielles Preisänderungsausmaß.\nZeigt den historischen maximalen Rückgang des Assets.',
        'metric.agr.description': 'AGR (Adaptive Growth Rate)\nJahresrendite unter Berücksichtigung von\nTrendkorrelation, Wachstum, Momentum und Stabilität.\nHauptsignal zur Wahl der Handelsrichtung.',
        'metric.din.description': 'DIN (Dynamic Impact)\nGewichtete Preisänderung unter Berücksichtigung\nvon Marktfaktoren (FGI, BTC Dom, OI, FR, LSR)\nund Momentum (CPT).',
        'metric.cpt.description': 'CPT (Composite Performance)\nKomposites Momentum: gewichteter Durchschnitt\nvon Preisänderungen über alle Zeitknoten\nunter Berücksichtigung des Prognosehorizonts.',
        'metric.fgi.description': 'Fear & Greed Index (FGI)\nIndikator der Marktstimmung. Hilft,\nÜberkauftheit oder Überverkauftheit zu erkennen.\n\n© Alternative.me',
        'metric.btcDom.description': 'BTC Dominance\nAnteil der Bitcoin-Marktkapitalisierung am Gesamtmarkt.\nZeigt Kapital-Konzentration in BTC\nund eine Risiko-aversive Stimmung.',
        'metric.oi.description': 'Open Interest (OI)\nGesamtvolumen offener Derivate-Positionen.\nSteigendes OI verstärkt Trends,\nfallendes OI signalisiert nachlassendes Interesse.',
        'metric.fr.description': 'Funding Rate (FR)\nFinanzierungsrate für Perpetual-Futures.\nPositiv — Longs dominieren,\nnegativ — Shorts dominieren.',
        'metric.lsr.description': 'Long/Short Ratio (LSR)\nVerhältnis von Long- zu Short-Positionen.\n>1 — Longs dominieren,\n<1 — Shorts dominieren.',
        'metric.vix.description': 'VIX (Volatility Index)\nVolatilitätsindex des US-Aktienmarkts.\nSteigender VIX signalisiert meist Angst\nund geringere Risikobereitschaft.'
    };

    const TOOLTIPS_ZH = {
        'button.save.icon': '图标：保存',
        'button.save.text': '主文本：保存更改',
        'button.delete.icon': '图标：删除',
        'button.delete.text': '主文本：删除元素',
        'button.load.icon': '图标：加载',
        'button.load.text': '主文本：加载文件',
        'button.settings.icon': '图标：设置',
        'button.settings.text': '主文本：打开设置',
        'button.save-all.text': '主文本：保存所有更改',
        'button.settings-app.text': '主文本：打开应用设置',
        'button.notifications.icon': '图标：通知',
        'button.notifications.text': '主文本：查看通知',
        'button.notifications.suffix.badge': '后缀：5 条新通知',
        'button.notifications.suffix.badge1': '后缀 1：5 条新通知',
        'button.notifications.suffix.badge2': '后缀 2：新功能',
        'button.export.icon': '图标：导出',
        'button.export.text': '主文本：导出数据',
        'button.export.suffix.icon': '后缀：在新标签页打开',
        'button.connection.icon': '图标：连接',
        'button.connection.text': '主文本：连接状态',
        'button.connection.suffix.indicator': '后缀：状态：已激活',
        'button.menu.text': '主文本：展开菜单',
        'button.menu.suffix.chevron': '后缀：展开/收起菜单',
        'button.help.icon': '图标：帮助',
        'button.help.text': '主文本：打开帮助',
        'button.help.suffix.info': '后缀：打开帮助',
        'dropdown.market-analytics.icon': '图标：市场分析',
        'dropdown.market-analytics.text': '主文本：查看统计',
        'dropdown.notifications.suffix.badge': '通知数量',
        'dropdown.notifications.icon': '图标：通知',
        'dropdown.notifications.text': '主文本：查看通知',
        'dropdown.system-settings.icon': '图标：系统设置',
        'dropdown.system-settings.text': '主文本：系统配置',
        'dropdown.export.suffix.icon': '在新标签页打开',
        'dropdown.export.icon': '图标：导出',
        'dropdown.export.text': '主文本：导出数据',
        'dropdown.connection.suffix.indicator': '状态：已激活',
        'dropdown.connection.icon': '图标：连接',
        'dropdown.connection.text': '主文本：连接状态',
        'dropdown.settings.suffix.chevron.expand': '展开子菜单',
        'dropdown.settings.icon': '图标：设置',
        'dropdown.settings.text': '主文本：设置',
        'dropdown.settings.suffix.chevron.collapse': '收起子菜单',
        'dropdown.analytics.suffix.info': '打开帮助',
        'dropdown.analytics.icon': '图标：分析',
        'dropdown.analytics.text': '主文本：高级分析',
        'dropdown.blocked.icon': '图标：已阻止',
        'dropdown.blocked.text': '主文本：功能不可用',
        'dropdown.document.suffix.badge': '新功能',
        'dropdown.document.icon': '图标：文档',
        'dropdown.document.text': '主文本：长文本',
        'ui.coinSort.alphabet': '字母 (A→Z)',
        'ui.coinSort.marketCap': '市值',
        'ui.coinSort.volume': '成交量',
        'ui.coinSort.favorite': '收藏',
        'ui.coinSort.selected': '已选',
        'ui.coinSet.load': '加载币种集合',
        'ui.coinSet.save': '保存币种集合',
        'ui.refresh.soft': '刷新界面（缓存有效）',
        'ui.refresh.full': '刷新币种数据和市场指标',
        'ui.coinTable.showPrice': '显示价格',
        'ui.coinTable.hidePrice': '隐藏价格',
        'ui.vix.sourcePrefix': 'VIX 来源：',
        'ui.vix.default': 'VIX 波动率指数',
        'ui.search.alreadyInTable': '已在表中',
        'ui.modal.missingCoins.title': '未找到币种',
        'ui.modal.portfolioForm.title': '创建投资组合',
        'ui.modal.portfolioView.title': '查看投资组合',
        'ui.combobox.clear': '清除',
        'ui.coinBlock.favorite.remove': '移除',
        'ui.coinBlock.favorite.add': '添加',
        'ui.coinBlock.open': '打开',
        'ui.coinBlock.delete': '删除',
        'ui.coinSet.draft.save': '保存草稿',
        'metric.horizonDays.description': '预测天数\n计算所有指标的时间范围。\n决定资产价格变化预测的\n时间跨度。',
        'metric.mdnHours.description': 'MDN 小时\n计算市场方向指标（MDN）的时间范围。\n短期“此时此刻”信号。',
        'metric.agrMethod.description': 'AGR 方法\nAGR 趋势稳定性计算方法：\nDCS（方向）、TSI（强度）、MP（动量）。',
        'metric.columnVisibility.description': '列可见性\n控制表格中列组的显示：\n主要指标、波动性、稳定性等。',
        'metric.columnVisibility.percent.description': '%（价格变化）\n显示不同时期的价格变化：\n1h, 24h, 7d, 14d, 30d, 200d。\n用于评估短期与长期趋势。',
        'metric.columnVisibility.complexDeltas.description': '复合增量（CD）\n按周累计的加权价格变化（CD1w–CD6w）\n以及预测区间的变化（CDH）。\n体现带时间权重的综合动态。',
        'metric.columnVisibility.gradients.description': '梯度（CGR）\n时间节点间的加权价格梯度（CGR2–CGR6）\n及其总和（CGR Σ）。\n显示价格变化的速度与方向。',
        'metric.columnVisibility.result.description': 'AGR: Adaptive Growth Rate\nMAX: Maximum Potential Value\nmin: Minimum Potential Value\nDCS: Direction Change Stability\nTSI: Trend Strength Indicator\nMPS: Momentum Preservation Stability\nCPT: Composite Performance\nDIN: Dynamic Impact',
        'metric.portfolioAccess.description': '我的投资组合\n快速访问已创建的组合，\n查看当前收益并创建新币种集合。',
        'metric.portfolioAccess.lsHeader': 'L/S 计数：',
        'metric.portfolioAccess.lsLong': 'Long (AGR ≥ 0)',
        'metric.portfolioAccess.lsShort': 'Short (AGR < 0)',
        'metric.mdn.description': 'MDN（Market Direction Now）\n当前市场方向的综合指标。\n考虑动量、趋势、中位数加速度\n及市场指标。',
        'metric.medianCdh.description': 'CDH 中位数\n所有币种累计增量（CDH）的中位数。\n显示预测区间的平均价格变化潜力。\n正值为看涨信号，负值为看跌信号。',
        'metric.medianCgr.description': 'CGR 中位数\n所有币种价格梯度（CGR）的中位数。\n显示市场运动的平均速度。\n正值为上涨加速，负值为下跌加速。',
        'metric.medianAgr.description': 'AGR 中位数\n所有币种自适应收益（AGR）的中位数。\n显示考虑趋势稳定性的平均年化潜力。\n正值看涨，负值看跌。',
        'metric.longShort.description': 'Long/Short\n看涨与看跌币种数量比例。\n显示市场广度——情绪在资产中的分布。',
        'metric.bullishPercent.description': 'Bullish Percent\n正向动态币种比例。\n显示牛市广度。\n高值 (>50%) — 广泛牛市，\n低值 (<50%) — 狭窄牛市或熊市。',
        'metric.cdhRatio.description': 'CDH P/N 比率\n正负 CDH 值的比率。\n显示累计增量的多空平衡。\n>1 看涨，<1 看跌。',
        'metric.cgrRatio.description': 'CGR P/N 比率\n正负 CGR 值的比率。\n显示上涨/下跌加速度的平衡。\n>1 上涨占优，<1 下跌占优。',
        'metric.agrRatio.description': 'AGR P/N 比率\n正负 AGR 值的比率。\n显示自适应收益的多空平衡。\n>1 看涨，<1 看跌。',
        'metric.dcs.description': 'DCS（Direction Change Stability）\n基于方向变化分析的 AGR 趋势稳定性方法。\n适用于高波动市场。',
        'metric.tsi.description': 'TSI（Trend Strength Indicator）\n基于趋势强度的 AGR 趋势稳定性方法。\n适用于稳定趋势行情。',
        'metric.mp.description': 'MPS（Momentum Preservation Stability）\n基于动量保持的 AGR 趋势稳定性方法。\n适用于动量市场。',
        'metric.cdh.description': 'CDH（Complex Delta Horizon）\n预测区间内的累计价格增量。\n考虑所有时间周期的综合变化。',
        'metric.cgr.description': 'CGR（Complex Gradient Rate）\n复合价格梯度。\n显示所有节点上的价格变化速度与方向。',
        'metric.cgrDeg.description': 'CGR Degree（梯度等级）\n复合梯度变化的程度。\n显示价格运动加速或减速的强度。',
        'metric.maxPV.description': 'Max PV（Maximum Potential Value）\n最大潜在价格变化。\n显示资产历史最大上涨幅度。',
        'metric.minPV.description': 'Min PV（Minimum Potential Value）\n最小潜在价格变化。\n显示资产历史最大下跌幅度。',
        'metric.agr.description': 'AGR（Adaptive Growth Rate）\n考虑趋势相关性、增长、动量和稳定性的年化收益。\n主要交易方向信号。',
        'metric.din.description': 'DIN（Dynamic Impact）\n考虑市场因素（FGI、BTC Dom、OI、FR、LSR）\n与动量（CPT）的加权价格变化。',
        'metric.cpt.description': 'CPT（Composite Performance）\n复合动量：考虑预测区间的\n所有时间节点价格变化的加权平均。',
        'metric.fgi.description': 'Fear & Greed Index（FGI）\n市场情绪指标，用于识别\n超买或超卖状态。\n\n© Alternative.me',
        'metric.btcDom.description': 'BTC Dominance\n比特币市值占总市场的比例。\n显示资金向 BTC 集中程度\n及风险规避情绪。',
        'metric.oi.description': 'Open Interest (OI)\n衍生品未平仓总量。\nOI 上升加强趋势，\nOI 下降表示兴趣减弱。',
        'metric.fr.description': 'Funding Rate (FR)\n永续合约资金费率。\n正值—多头占优，\n负值—空头占优。',
        'metric.lsr.description': 'Long/Short Ratio (LSR)\n多空持仓比例。\n>1 — 多头占优，\n<1 — 空头占优。',
        'metric.vix.description': 'VIX（Volatility Index）\n美国股市波动率指数。\nVIX 上升通常意味着恐慌\n和风险偏好下降。'
    };

    function getTooltip(key) {
        if (currentLanguage === 'ru') return TOOLTIPS_RU[key] || key;
        if (currentLanguage === 'en') return TOOLTIPS_EN[key] || TOOLTIPS_RU[key] || key;
        if (currentLanguage === 'de') return TOOLTIPS_DE[key] || TOOLTIPS_EN[key] || TOOLTIPS_RU[key] || key;
        if (currentLanguage === 'zh') return TOOLTIPS_ZH[key] || TOOLTIPS_EN[key] || TOOLTIPS_RU[key] || key;
        return TOOLTIPS_EN[key] || TOOLTIPS_RU[key] || key;
    }

    async function init(language) {
        if (!language) language = 'ru';

        // Всегда устанавливаем currentLanguage сначала
        currentLanguage = language;

        if (language === 'ru' || language === 'en' || language === 'de' || language === 'zh') {
            return;
        }
        // Фолбэк на английский for неподдерживаемых языков
        currentLanguage = 'en';
    }

    window.tooltipsConfig = {
        TOOLTIPS: TOOLTIPS_RU,
        TOOLTIPS_EN: TOOLTIPS_EN,
        TOOLTIPS_DE: TOOLTIPS_DE,
        TOOLTIPS_ZH: TOOLTIPS_ZH,
        getTooltip,
        init,
        getCurrentLanguage: () => currentLanguage
    };
    console.log('tooltips-config.js: initialized with en support');
})();
